<?xml version="1.0" encoding="utf-8"?><Database Name="curs" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-3U6D185\SQLEXPRESS;Initial Catalog=curs;Integrated Security=True;Pooling=False" SettingsObjectName="curs._1.Properties.Settings" SettingsPropertyName="cursConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Car" Member="Car">
    <Type Name="Car">
      <Column Name="id_car" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="brand" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="carrying_capacity" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="width" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="heigth" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Car_Order" Member="Order" ThisKey="id_car" OtherKey="id_car" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Client">
    <Type Name="Client">
      <Column Name="id_client" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="company" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Client_Order" Member="Order" ThisKey="id_client" OtherKey="id_client" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Driver" Member="Driver">
    <Type Name="Driver">
      <Column Name="id_driver" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="date_of_birth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="passport_number" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="adress" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Driver_Order" Member="Order" ThisKey="id_driver" OtherKey="id_driver" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Order">
    <Type Name="Order">
      <Column Name="id_order" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_driver" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_car" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_client" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="point_of_departure" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="point_of_arrival" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="weight" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="width" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="height" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="type_cargo" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="reg_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="cost" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="paid" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="Order_Profit_driver" Member="Profit_driver" ThisKey="id_order" OtherKey="id_order" Type="Profit_driver" />
      <Association Name="Car_Order" Member="Car" ThisKey="id_car" OtherKey="id_car" Type="Car" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Client_Order" Member="Client" ThisKey="id_client" OtherKey="id_client" Type="Client" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Driver_Order" Member="Driver" ThisKey="id_driver" OtherKey="id_driver" Type="Driver" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Profit_driver" Member="Profit_driver">
    <Type Name="Profit_driver">
      <Column Name="id_profit_driver" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_driver" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Order_Profit_driver" Member="Order" ThisKey="id_order" OtherKey="id_order" Type="Order" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>